01-Implementation/haeun/백준_거북이.cpp
01-Implementation/haeun/백준_빙고.cpp
01-Implementation/haeun/백준_왕복.cpp
01-Implementation/haeun/백준_주사위 굴리기.cpp
01-Implementation/haeun/프로그래머스_모음사전.cpp
01-Implementation/haeun/프로그래머스_카펫.cpp
01-Implementation/haeun/프로그래머스_피로도.cpp

- https://velog.io/@jxlhe46/백준-18311번.-왕복
- https://velog.io/@jxlhe46/백준-8911번.-거북이
- https://velog.io/@jxlhe46/백준-2578번.-빙고
- https://velog.io/@jxlhe46/프로그래머스-피로도
- https://velog.io/@jxlhe46/프로그래머스-모음사전
- 주사위 굴리기 문제는 아직 제 수준에 많이 어려워서,,, 다른 구현 문제로 대체해서 풀었습니다! (백준 2578번. 빙고) 
- 선택 문제 3개는 프로그래머스 고득점 Kit에서 완탐 문제 골라서 풀었어요! 
- 비교적 쉬운 난이도의 카펫 문제는 따로 해설을 적지 않았습니다.

[Week 1] Implementation - 하은

---

01-Implementation/Sunny/거북이.java
01-Implementation/Sunny/베스트앨범.java
01-Implementation/Sunny/왕복.java
01-Implementation/Sunny/위장.java
01-Implementation/Sunny/주사위굴리기.java
01-Implementation/Sunny/타겟넘버.java
02-Stack&Queue/Sunny/괄호제거.java

---
- 백준 14499번(주사위 굴리기) - 골드 4 (https://www.acmicpc.net/problem/14499)
- 백준 18311번(왕복) - 실버 5 (https://www.acmicpc.net/problem/18311)
- 백준 8911번(거북이) - 실버 2 (https://www.acmicpc.net/problem/8911)
- 프로그래머스 (베스트앨범, 해시) -Lv3 (https://school.programmers.co.kr/learn/courses/30/lessons/42579) (😅 풀이 보고 품.. ^^)
- 프로그래머스 (위장, 해시) - Lv2 (https://school.programmers.co.kr/learn/courses/30/lessons/42578)
- 프로그래머스 (타겟넘버, DFS&BFS) - Lv2 (https://school.programmers.co.kr/learn/courses/30/lessons/43165)

[Week 1] Implementation - 선희

---

01-Implementation/yongtaek/거북이.java
01-Implementation/yongtaek/덩치.java
01-Implementation/yongtaek/왕복.java
01-Implementation/yongtaek/주사위굴리기.java
01-Implementation/yongtaek/집합.java
01-Implementation/yongtaek/한줄로서기.java

- 18311 왕복 - 실버 5 https://www.acmicpc.net/problem/18311
- 8911 거북이 - 실버 2 https://www.acmicpc.net/problem/8911
- 14499 주사위 굴리기 - 골드 4 https://www.acmicpc.net/problem/14499
> 주사위 굴리기 / 많이 참고하여서 다시 풀 예정
- 11723 집합 - 실버 5 https://www.acmicpc.net/problem/11723
- 7568 덩치 - 실버 5 https://www.acmicpc.net/problem/7568
- 1138 한 줄로 서기 - 실버 2 https://www.acmicpc.net/problem/1138

[Week 1] Implementation - 용택

---

02-Stack&Queue/haeun/백준_AC.md
02-Stack&Queue/haeun/백준_괄호제거.cpp
02-Stack&Queue/haeun/백준_프린터큐.md
02-Stack&Queue/haeun/프로그래머스_체육복.cpp

- https://velog.io/@jxlhe46/백준-1966번.-프린터-큐
- https://velog.io/@jxlhe46/백준-5430번.-AC
- https://velog.io/@jxlhe46/백준-2800번.-괄호-제거
- https://velog.io/@jxlhe46/프로그래머스-체육복 (그리디)

[Week 2] Stack & Queue - 하은

---

02-Stack&Queue/yongtaek/AC.java
02-Stack&Queue/yongtaek/균형잡힌세상.java
02-Stack&Queue/yongtaek/라우터.java
02-Stack&Queue/yongtaek/큐2.java
02-Stack&Queue/yongtaek/프린터큐.java

---
- 백준 1966 프린터 큐 - 실버3
- 백준 5430 AC - 골드5
- 백준 2800 괄호제거 - 골드5 (업로드 하겠습니다!)
- 백준 15828 라우터 - 실버4
- 백준 18258 큐2 - 실버4
- 백준 4949 균형잡힌 세상 - 실버4

[Week 2] Stack & Queue - 용택

---

02-Stack&Queue/chaerin/1966_프린터큐.py
02-Stack&Queue/chaerin/2800_괄호제거.py
02-Stack&Queue/chaerin/5430_AC.py

- 1966 프린터 큐 - 실버3 https://www.acmicpc.net/problem/1966
- 2800 괄호제거 - 골드5 https://www.acmicpc.net/problem/2800
- 5430 AC - 골드5 - https://www.acmicpc.net/problem/5430

[Week2] Stack&Queue - 채린

---

02-Stack&Queue/Sunny/AC.java
02-Stack&Queue/Sunny/괄호제거.java
02-Stack&Queue/Sunny/연구소.java
02-Stack&Queue/Sunny/올바른괄호.java
02-Stack&Queue/Sunny/주식가격.java
02-Stack&Queue/Sunny/프린터큐.java

---
- 백준 1966 프린터 큐 - 실버3
- 백준 2800 괄호제거 - 골드5
- 백준 5430 AC - 골드5
- 프로그래머스 올바른 괄호 (https://school.programmers.co.kr/learn/courses/30/lessons/12909)
- 프로그래머스 주식가격 (https://school.programmers.co.kr/learn/courses/30/lessons/42584)
- 백준 14502 연구실 (https://www.acmicpc.net/problem/14502)

[Week2] Stack&Queue - 선희

---

02-Stack&Queue/jooyoung/1966_프린터 큐.py
03-Heap/jooyoung/2075_N번째 큰.py

[Week 2] Stack&Queue - 주영

---

03-Heap/eugene/2075_N번째수.py
03-Heap/eugene/과일장수.py
03-Heap/eugene/기사단원의무기.py
03-Heap/eugene/더맵게.py
03-Heap/eugene/햄버거만들기.py

- 백준 2075 n번째 큰수
- 프로그래머스 더 맵게
- 백준 7662 이중 우선순위 큐 [not solved]
- 프로그래머스 과일장수
- 프로그래머스 기사단원의 무기
- 햄버거 만들

[WEEK3] Heap - 유진

---

03-Heap/haeun/백준_N번째 큰 수.cpp
03-Heap/haeun/백준_쇠막대기.cpp
03-Heap/haeun/백준_이중 우선순위 큐.cpp
03-Heap/haeun/프로그래머스_다리를 지나는 트럭.cpp
03-Heap/haeun/프로그래머스_더맵게.cpp
03-Heap/haeun/프로그래머스_디스크 컨트롤러.cpp

- https://velog.io/@jxlhe46/백준-2075번.-N번째-큰-수
- https://velog.io/@jxlhe46/백준-7662번.-이중-우선순위-큐
- https://velog.io/@jxlhe46/백준-10799번.-쇠막대기
- https://velog.io/@jxlhe46/프로그래머스-다리를-지나는-트럭
- https://velog.io/@jxlhe46/프로그래머스-디스크-컨트롤러
- 비교적 쉬운 문제였던 '더 맵게' 문제는 해설을 따로 작성하지 않았습니다..! 코드 보시면 이해하실 수 있을 거예요!

[Week 3] Heap - 하은

---

03-Heap/jooyoung/2075_N번째 큰.py
03-Heap/jooyoung/7662_이중 우선순위 큐.py
03-Heap/jooyoung/더 맵게.py

[Week 3] Heap - 주영

---

03-Heap/chaerin/2075_N번째큰수.py
03-Heap/chaerin/test1.py
03-Heap/chaerin/test2.py
03-Heap/chaerin/test3.py
03-Heap/chaerin/test4.py
03-Heap/chaerin/test5.py

제가 이번주에 목요일까지 시험을 치는 바람에 주차별 문제는 한문제밖에 못 풀었습니다ㅜㅠ
다음주는 꼭 다 풀도록 할게요!
2075 N번째 큰수 - 실버2 https://www.acmicpc.net/problem/2075
+) 이번주에 본 코테에서 나온 문제들 풀이 같이 올렸습니다.

[Week3] Heap - 채린

---

03-Heap/yongtaek/N번째큰수.java
03-Heap/yongtaek/더맵게.java
03-Heap/yongtaek/이중우선순위큐.java
03-Heap/yongtaek/절대값힙.java
03-Heap/yongtaek/최대힙.java
03-Heap/yongtaek/최소힙.java

🐬공통문제
- 백준 2075 n번째 큰수
- 프로그래머스 더 맵게
- 백준 7662 이중 우선순위 큐
🐬자유문제
- 백준 1927 최소힙
- 백준 11279 최대힙
- 백준 11286 절대값 힙

[Week 3] Heap - 용택

---

04-DFS&BFS/jooyoung/1260_DFS와BFS.py
04-DFS&BFS/jooyoung/16236_아기상어.py
04-DFS&BFS/jooyoung/1697_숨바꼭질.py
04-DFS&BFS/jooyoung/sw_1954.py

[Week4] DFS&BFS - 주영

---

04-DFS&BFS/chaerin/1012_유기농배추.py
04-DFS&BFS/chaerin/1260_DFS와BFS.py
04-DFS&BFS/chaerin/162356_아기상어.py
04-DFS&BFS/chaerin/1697_숨바꼭질.py

1260 DFS와 BFS - 실버2 https://www.acmicpc.net/problem/1260
1697 숨바꼭질 실버1 https://www.acmicpc.net/problem/1697
16236 아기상어 골드3 https://www.acmicpc.net/problem/16236
1012 유기농배추 실버2 https://www.acmicpc.net/problem/1012

[Week 4] BFS&DFS-채린

---

04-DFS&BFS/haeun/백준_DFS_BFS.cpp
04-DFS&BFS/haeun/백준_숨바꼭질.cpp
04-DFS&BFS/haeun/백준_아기상어.cpp
04-DFS&BFS/haeun/프로그래머스_단어 변환.cpp

- DFS와 BFS: https://velog.io/@jxlhe46/알고리즘-DFSBFS
- 숨바꼭질: https://velog.io/@jxlhe46/백준-1697번.-숨바꼭질
- 아기상어: https://velog.io/@jxlhe46/백준-16236번.-아기-상어
- 단어 변환: https://velog.io/@jxlhe46/프로그래머스-단어-변환
- 코드에도 모두 주석을 달아뒀어요!

[Week 4] DFS&BFS - 하은

---

04-DFS&BFS/jiyeon/1260_DFS와BFS
04-DFS&BFS/jiyeon/16236_아기상어
04-DFS&BFS/jiyeon/1697_숨바꼭질
04-DFS&BFS/jiyeon/9461_파도반수열

💦 필수 문제
1260 DFS와 BFS - 실버2 https://www.acmicpc.net/problem/1260
1697 숨바꼭질 실버1 https://www.acmicpc.net/problem/1697
16236 아기상어 골드3 https://www.acmicpc.net/problem/16236
🐬자유 문제
9461 파도반 수열

[Week 4] DFS&BFS -지연

---

04-DFS&BFS/hayoun/백준1260.cpp
04-DFS&BFS/hayoun/백준14503.cpp
04-DFS&BFS/hayoun/백준16236.cpp
04-DFS&BFS/hayoun/백준1697.cpp

- 백준 1260 DFS와 BFS - 실버2 https://www.acmicpc.net/problem/1260
- 백준 1697 숨바꼭질 실버1 https://www.acmicpc.net/problem/1697
- 백준 16236 아기상어 골드3 https://www.acmicpc.net/problem/16236 
- 백준 14503 로봇청소기 골드5 https://www.acmicpc.net/problem/14503 
화이팅!

[Week 4] DFS & BFS - 하윤

---

04-DFS&BFS/yongtaek/DFS와BFS.java
04-DFS&BFS/yongtaek/숨바꼭질.java
04-DFS&BFS/yongtaek/아기상어.java
04-DFS&BFS/yongtaek/토마토.java

필수 문제
1260 DFS와 BFS - 실버2 https://www.acmicpc.net/problem/1260
1697 숨바꼭질 실버1 https://www.acmicpc.net/problem/1697
16236 아기상어 골드3 https://www.acmicpc.net/problem/16236
자유 문제
7569 토마토 https://www.acmicpc.net/problem/7569

[Week4] DFS & BFS - 용택

---

04-DFS&BFS/Sunny/2개 이하로 다른 비트.java
04-DFS&BFS/Sunny/DFS와 BFS.java
04-DFS&BFS/Sunny/숨바꼭질.java
04-DFS&BFS/Sunny/아기상어.java

---
- 1260 DFS와 BFS - 실버2 https://www.acmicpc.net/problem/1260
- 1697 숨바꼭질 실버1 https://www.acmicpc.net/problem/1697
- 16236 아기상어 골드3 https://www.acmicpc.net/problem/16236 
- 프로그래머스 2개 이하로 다른 비트 https://school.programmers.co.kr/learn/courses/30/lessons/77885

[Week 4] DFS&BFS - 선희

---

04-DFS&BFS/1260_DFS와BFS.py
04-DFS&BFS/1697_숨바꼭질.py
04-DFS&BFS/소수찾기.py

- 백준 1260 DFS와 BFS
- 백준 1967 숨바꼭질
- 백준 12236 아기상어 [unsolved]
- 프로그래머스 소수 찾기
[1. DFS와BFS](#DFS-와-BFS)
[2. 숨바꼭질](#숨바꼭질)
[3. 아기상어](#아기상어)
[4. 소수찾기](#소수찾기)
> Hoxy...12시 1분에 제출했는데 다들 봐주시나요^^...?
> plz....사유는 밑에 나옵니다
<br>
```python
def dfs(v):
visited[v] = 1 
print(v, end=' ')                        # 띄어쓰기가 있으므로 end = '' 사용
for i in range(1, n+1):
if visited[i] == 0 and maps[v][i] == 1: # 방문하지 않고 연결된 노드 일 경우
dfs(i)                          # 재귀
def bfs(v):
queue = [v] 
visited[v] = 0 
while queue:
v = queue.pop(0) 
print(v,end=' ') 
for i in range(1 , n+1):
if(visited[i] == 1 and maps[v][i] == 1):# 방문하지 않고 연결된 노드 일 경우
queue.append(i)
visited[i] = 0
```
<br>
우선 DFS와 BFS는 재귀 함수로 따로 만들어 줬습니다.  
모두 띄어쓰기가 있도록 출력해야 했기 때문에 `end=' '` 를 사용해 줬습니다.
```python
for i in range(m):
a,b = …
```

[WEEK4] DFS&BFS - 유진

---

04-DFS&BFS/1260_DFS와BFS.cpp
04-DFS&BFS/1697_숨바꼭질.cpp
04-DFS&BFS/18185_라면사기.cpp

백준 1260 DFS와 BFS - 실버2 https://www.acmicpc.net/problem/1260
백준 1697 숨바꼭질 실버1 https://www.acmicpc.net/problem/1697
백준 16236 아기상어 골드3 https://www.acmicpc.net/problem/16236 미해결
백준 18185 라면사기 다이아5 https://www.acmicpc.net/problem/18185

[Week 4] DFS & BFS - 재훈

---

05-BruteForce/sookyung/1,2,3더하기.py
05-BruteForce/sookyung/다음순열.py
05-BruteForce/sookyung/분해합.py
05-BruteForce/sookyung/영화감독숌.py

필수문제
9095 1,2,3 더하기 - https://www.acmicpc.net/problem/9095
10972 다음 순열 - https://www.acmicpc.net/problem/10972
자유문제
1436 영화감독 숌 https://www.acmicpc.net/problem/1436
2231 분해합 https://www.acmicpc.net/problem/2231

[Week 5] Brute Force -수경

---

05-BruteForce/Sunny/1, 2, 3 더하기.java
05-BruteForce/Sunny/다음 순열.java
05-BruteForce/Sunny/숫자의 표현.java
05-BruteForce/Sunny/연산자 끼워넣기.java

---
- 9095 1,2,3 더하기 - https://www.acmicpc.net/problem/9095
- 10972 다음 순열 - https://www.acmicpc.net/problem/10972
- 프로그래머스 숫자의 표현 - https://school.programmers.co.kr/learn/courses/30/lessons/12924
- 14888 연산자 끼워넣기 - https://www.acmicpc.net/problem/14888

[Week 5] Brute Force - 선희

---

05-BruteForce/jooyoung/10972_다음순열.py
05-BruteForce/jooyoung/9095_1 2 3더하기.py
05-BruteForce/jooyoung/스택큐_같은 숫자는 싫어.py
05-BruteForce/jooyoung/하샤드 수.py

- 9095 1,2,3 더하기 - https://www.acmicpc.net/problem/9095
- 10972 다음 순열 - https://www.acmicpc.net/problem/10972
- 연습문제 하샤드 수 - https://school.programmers.co.kr/learn/courses/30/lessons/12947
- 스택큐 같은 숫자는 싫어 - https://school.programmers.co.kr/learn/courses/30/lessons/12906

[Week 5] BruteForce - 주영

---

05-BruteForce/haeun/10972_다음 순열.cpp
05-BruteForce/haeun/1969_DNA.cpp
05-BruteForce/haeun/9095_1, 2, 3 더하기.md

- https://velog.io/@jxlhe46/백준-9095번.-1-2-3-더하기
- https://velog.io/@jxlhe46/백준-10972번.-다음-순열
- https://velog.io/@jxlhe46/백준-1969번.-DNA (지각 제출)

[Week 5] BruteForce - 하은

---

05-BruteForce/yongtaek/다음순열.java
05-BruteForce/yongtaek/더하기.java
05-BruteForce/yongtaek/체스판다시칠하기.java

- 9095 1,2,3 더하기 - https://www.acmicpc.net/problem/9095
- 10972 다음 순열 - https://www.acmicpc.net/problem/10972
- 1018 체스판 다시칠하기 - https://www.acmicpc.net/problem/1018

[Week5] Brute Force - 용택

---

05-BruteForce/10972_다음순열.cpp
05-BruteForce/11000_강의실배정.cpp
05-BruteForce/20365_블로그2.cpp
05-BruteForce/9095_1,2,3더하기.cpp
06-DP/10808_알파벳 개수.cpp
06-DP/1463.cpp
06-DP/1520_내리막길.cpp
06-DP/2979_트럭주차.cpp

[Week5] Brute Force - 재훈

---

05-BruteForce/hayoun/백준10972.cpp
05-BruteForce/hayoun/백준9019.cpp
05-BruteForce/hayoun/백준9095.cpp
05-BruteForce/hayoun/키패드누르기.cpp

9095 1,2,3 더하기 - https://www.acmicpc.net/problem/9095
10972 다음 순열 - https://www.acmicpc.net/problem/10972
9019 백준 DSLR - https://www.acmicpc.net/problem/9019
프로그래머스 키패드 누르기 - https://school.programmers.co.kr/learn/courses/30/lessons/67256

[Week 5] Brute Force - 하윤

---

05-BruteForce/Eugene/1520_내리막길.py
05-BruteForce/Eugene/9095_123더하기.py
05-BruteForce/Eugene/프로그래머스_문자열 압축.py

- 9095 1,2,3 더하기
- 10972 다음 순열
- 프로그래머스 문자열 압축
[1. 1,2,3 더하기](#123더하기)
[2. 다음 순열](#다음-순열)
[3. 문자열 압축](#문자열-압축)
<br>
점심....먹기위해 이후 설명 작성...
```python
m,n = map(int, input().split())
maps = [list(map(int, input().split())) for _ in range(m)]
visited = [[-1] * n for _ in range(m)]    # 방문 여부 확인
def dfs(x, y):
cnt = 0
dx = [1, -1, 0, 0]
dy = [0, 0, 1, -1]
if x == m-1 and y == n-1:             # 끝까지 도달하는 경우
return 1
if visited[x][y] != -1:               # 이미 더 낮다는걸 확인 한 경우
return visited[x][y]
for i in range(4):                     # 4방향 탐색
nx = x + dx[i]
ny = y + dy[i]
if 0 <= nx < m and 0 <= ny < n:    # 맵 안에 있는 경우  
if maps[x][y] > maps[nx][ny]:  # 갈 수 있는 경우
cnt += dfs(nx, ny)                # 죽지 않고 돌아온 재귀함수
visited[x][y] = cnt
return visited[x][y]
print(dfs(0,0))
```
```python
T = …
```

[Week 5] BruteForce - 유진

---

06-DP/Sunny/1로 만들기.java
06-DP/Sunny/귤 고르기.java
06-DP/Sunny/기능개발.java
06-DP/Sunny/내리막길.java

---
- 1463 1로 만들기 실버 3 - https://www.acmicpc.net/problem/1463
- 1520 내리막 길 골드 3 - https://www.acmicpc.net/problem/1520
- 프로그래머스 귤 고르기 - https://school.programmers.co.kr/learn/courses/30/lessons/138476
- 프로그래머스 기능 개발 - https://school.programmers.co.kr/learn/courses/30/lessons/42586

[Week6] DP - 선희

---

06-DP/yongtaek/RGB거리.java
06-DP/yongtaek/내리막길.java
06-DP/yongtaek/연속합.java
06-DP/yongtaek/일로만들기.java

---
- 1463 1로 만들기 실버 3 - https://www.acmicpc.net/problem/1463
- 1520 내리막 길 골드 3 - https://www.acmicpc.net/problem/1520
- RGB거리 https://www.acmicpc.net/problem/1149
- 연속합 https://www.acmicpc.net/problem/1912

[Week 6] DP - 용택

---

06-DP/haeun/1149_RGB 거리.cpp
06-DP/haeun/1463_1로 만들기.md
06-DP/haeun/1520_내리막길.cpp
06-DP/haeun/2579_계단 오르기.cpp

- https://velog.io/@jxlhe46/백준-1463번.-1로-만들기
- https://velog.io/@jxlhe46/백준-1520번.-내리막길
- https://velog.io/@jxlhe46/백준-1149번.-RGB-거리
- https://velog.io/@jxlhe46/백준-2579번.-계단-오르기

[Week 6] DP - 하은

---

06-DP/jooyoung/1463_1로 만들기.py
06-DP/jooyoung/완전탐색_최소직사각형.py
06-DP/jooyoung/정렬_k번째수.py

[week 6] DP - 주영

---

07-Greedy/haeun/17828_문자열 화폐.cpp
07-Greedy/haeun/1789_수들의 합.cpp

- https://velog.io/@jxlhe46/백준-1789번.-수들의-합
- 문자열 화폐 문제는 주석 확인해주세요!
- 자유 문제 2개 못 풀어서 벌금 내겠습니다,,

[Week7] Greedy - 하은

---

07-Greedy/Eugene/17828문자열화폐.py
07-Greedy/Eugene/1789수들의합.py
07-Greedy/Eugene/프로그래머스-비밀지도.py
07-Greedy/Eugene/프로그래머스-튜플.py
08-Graph/Eugene/1012유기농배추.py
08-Graph/Eugene/7569토마토.py
08-Graph/Eugene/숫자짝꿍.py

17828 문자열 화폐 골드5 - https://www.acmicpc.net/problem/17828
1789 수들의 합 실버5 - https://www.acmicpc.net/problem/1789
프로그래머스 튜플 - https://school.programmers.co.kr/learn/courses/30/lessons/64065
프로그래머스 비밀지도 - https://school.programmers.co.kr/learn/courses/30/lessons/17681
_드디어... 노 벌금^^..._

[Week 7] Greedy - 유진

---

07-Greedy/chaerin/1463_1로만들기.py
07-Greedy/chaerin/1520_내리막길.py
07-Greedy/chaerin/17828_문자열화폐.py
07-Greedy/chaerin/1789_수들의합.py

1463 1로 만들기 실버 3 - https://www.acmicpc.net/problem/1463
1520 내리막 길 골드 3 - https://www.acmicpc.net/problem/1520
17828 문자열 화폐 골드5 - https://www.acmicpc.net/problem/17828
1789 수들의 합 실버5 - https://www.acmicpc.net/problem/1789

[Week7] Greedy - chaerin

---

07-Greedy/문자열화폐.java
07-Greedy/수들의합.java
07-Greedy/잃어버린괄호.java
07-Greedy/회의실배정.java

고정 문제 
- 백준 1789 수들의 합
- 백준 17828 문자열 화폐
자유 문제
- 백준 1541 잃어버린 괄호
- 백준 1931 회의실 배정

[Week 7] Greedy - 용택

---

07-Greedy/Sunny/가장 큰 수.java
07-Greedy/Sunny/다리를 지나는 트럭.java
07-Greedy/Sunny/문자열 화폐.java
07-Greedy/Sunny/수들의 합.java
08-Graph/Sunny/땅따먹기.java
08-Graph/Sunny/소수 찾기.java
08-Graph/Sunny/유기농 배추.java
08-Graph/Sunny/토마토.java

---
- 17828 문자열 화폐 골드5 - https://www.acmicpc.net/problem/17828
- 1789 수들의 합 실버5 - https://www.acmicpc.net/problem/1789
- 프로그래머스 가장 큰 수 - https://school.programmers.co.kr/learn/courses/30/lessons/42746
- 프로그래머스 다리를 지나는 트럭 - https://school.programmers.co.kr/learn/courses/30/lessons/42583

[Week 7] Greedy - 선희

---

08-Graph/haeun/1012_유기농 배추.cpp
08-Graph/haeun/7569_토마토.cpp
08-Graph/haeun/7576_토마토.cpp
08-Graph/haeun/전력망을 둘로 나누기.cpp

- https://velog.io/@jxlhe46/백준-1012번.-유기농-배추
- https://velog.io/@jxlhe46/백준-7576-7569-토마토
- https://velog.io/@jxlhe46/프로그래머스-전력망을-둘로-나누기

[Week 8] Graph - 하은

---

08-Graph/jiyeon/1012_유기농배추
08-Graph/jiyeon/20006_랭킹전대기열
08-Graph/jiyeon/7569_토마토
08-Graph/jiyeon/다리를지나는트럭

🥨고정 문제
- [백준] 7569 토마토
- [백준] 1012 유기농 배추
🐤자유 문제
- [백준] 20006 랭킹전 대기열
- [프로그래머스] 다리를 지나는 트럭

[Week 8] Graph - 지연

---

08-Graph/Sunny/땅따먹기.java
08-Graph/Sunny/소수 찾기.java
08-Graph/Sunny/유기농 배추.java
08-Graph/Sunny/토마토.java

---
- 7569 토마토 골드5 https://www.acmicpc.net/problem/7569
- 1012 유기농 배추 실버2 https://www.acmicpc.net/problem/1012
- 프로그래머스 소수 찾기 - https://school.programmers.co.kr/learn/courses/30/lessons/42839
- 프로그래머스 땅따먹기 - https://school.programmers.co.kr/learn/courses/30/lessons/12913

[Week 8] Graph - 선희

---

08-Graph/chaerin/1012_유기농배추.py
08-Graph/chaerin/14_longest_common_prefix.py
08-Graph/chaerin/21_merge_two_sorted_list.py
08-Graph/chaerin/7569_토매이러.py

7569 토마토 골드5 https://www.acmicpc.net/problem/7569
1012 유기농 배추 실버2 https://www.acmicpc.net/problem/1012
14 longest-common-prefix https://leetcode.com/problems/longest-common-prefix
21 merge-two-sorted-lists https://leetcode.com/problems/merge-two-sorted-lists
면접에서 라이브 코딩 시키면 leetcode로 보는 곳이 꽤 있다고 들어서 leetcode 풀어봤어요!
보통 라이브 코딩은 easy 단계에서 나오는 것 같아요. 이건 interview top 100 링크입니다!
https://leetcode.com/problem-list/top-interview-questions

[Week 8] Graph - 채린

---

07-Greedy/hayoun/백준17828.cpp
07-Greedy/hayoun/백준1789.cpp
07-Greedy/hayoun/백준5430.cpp
07-Greedy/hayoun/코드트리빵.cpp

17828 문자열 화폐 골드5 - https://www.acmicpc.net/problem/17828
1789 수들의 합 실버5 - https://www.acmicpc.net/problem/1789
5430 AC 골드5 -https://www.acmicpc.net/problem/5430
코드트리 빵 골드2 https://www.codetree.ai/training-field/frequent-problems/problems/codetree-mon-bread/description?page=3&username=&pageSize=20

[Week 7] Greedy-하윤

---

08-Graph/Eugene/1012유기농배추.py
08-Graph/Eugene/7569토마토.py
08-Graph/Eugene/개인정보수집유효기간.py
08-Graph/Eugene/숫자짝꿍.py

- 1012 **유기농 배추**  https://www.acmicpc.net/problem/1012
- 7569 **토마토** https://www.acmicpc.net/problem/7569
---
- 프로그래머스 **숫자 짝꿍** https://school.programmers.co.kr/learn/courses/30/lessons/131128
- 프로그래머스 **개인정보 수집 유효기간** https://school.programmers.co.kr/learn/courses/30/lessons/150370
<br>
> 아니 그 와중에 폴더 다른데도 지 혼자서 같은 폴더에 넣어버려서... Revert..했습니다^^,,,

[WEEK 8] Graph - 유진

---

08-Graph/yongtaek/유기농배추.java

7569 토마토 골드5 https://www.acmicpc.net/problem/7569
1012 유기농 배추 실버2 https://www.acmicpc.net/problem/1012
2606 바이러스
2667 단지이름붙이기

[Week 8] Graph - 용택

---

08-Graph/jooyoung/7569_토마토.py
08-Graph/jooyoung/신규 아이디 추천.py
08-Graph/jooyoung/핸드폰 번호 가리기.py

[Waeek 8] Graph - 주영

---

09-BinarySearch/Sunny/랜선 자르기.java
09-BinarySearch/Sunny/선분 위의 점.java
09-BinarySearch/Sunny/숫자카드.java
09-BinarySearch/Sunny/입국심사.java

---
- 11663 선분 위의 점 실버3 https://www.acmicpc.net/problem/11663
- 3079 입국심사 골드5 https://www.acmicpc.net/problem/3079
- 1654 랜선 자르기 https://www.acmicpc.net/problem/1654
- 10816 숫자 카드 https://www.acmicpc.net/problem/10816

[Week 9] BinarySearch - 선희

---

09-BinarySearch/haeun/11663_선분 위의 점.md
09-BinarySearch/haeun/1654_랜선 자르기.cpp
09-BinarySearch/haeun/2805_나무 자르기.cpp
09-BinarySearch/haeun/3079_입국심사.cpp

- https://velog.io/@jxlhe46/백준-11663번.-선분-위의-점
- https://velog.io/@jxlhe46/백준-2805번.-나무-자르기
- https://velog.io/@jxlhe46/백준-1654번.-랜선-자르기
- https://velog.io/@jxlhe46/백준-3079번.-입국심사
- 나무 자르기, 랜선 자르기는 복습 삼아서 다시 풀고 블로그 내용도 수정했는데, 벨로그에는 최초 작성일만 보여서 포스팅 날짜가 최근이 아닌 점 참고해주세요!

[Week9] BinarySearch - 하은

---

09-BinarySearch/jiyeon/11663_선분위의점
09-BinarySearch/jiyeon/3079_입국심사
09-BinarySearch/jiyeon/개인정보수집유효기간
09-BinarySearch/jiyeon/택배배달과수거하기

고정 문제
[백준] 11663 선분 위의 점
[백준] 3079 입국 심사
자유 문제
[프로그래머스] 개인정보 수집 유효 기간
[프로그래머스] 택배 배달과 수거하기

[Week 9] BinarySearch - 지연

---

09-BinarySearch/sookyung/선분위의점.py
09-BinarySearch/sookyung/수찾기.py
09-BinarySearch/sookyung/입국심사.py
09-BinarySearch/sookyung/징검다리.py

**필수문제**
11663 선분 위의 점 실버3 https://www.acmicpc.net/problem/11663
3079 입국심사 골드5 https://www.acmicpc.net/problem/3079
**자유문제**
11561 징검다리 https://www.acmicpc.net/problem/11561
1920 수찾기 https://www.acmicpc.net/problem/1920

[Week 9] BinarySearch -수경

---

10-Dijkstra/haeun/11404_플로이드.cpp
10-Dijkstra/haeun/1446_지름길.cpp
10-Dijkstra/haeun/1753_최단경로.md
10-Dijkstra/haeun/18352_특정 거리의 도시 찾기.cpp

- https://velog.io/@jxlhe46/백준-1446번.-지름길
- https://velog.io/@jxlhe46/백준-18352번.-특정-거리의-도시-찾기
- https://velog.io/@jxlhe46/그리디-다익스트라-알고리즘
- https://velog.io/@jxlhe46/DP-플로이드-워셜-알고리즘 
- 자유 문제 2개는 다익스트라, 플로이드-워셜 기초 문제로 풀었습니다!

[Week10] Dijkstra - 하은

---

08-Graph/jaehoon/1012_유기농배추.cpp
08-Graph/jaehoon/10870_피보나치수5.cpp
08-Graph/jaehoon/2839_설탕배달.cpp
08-Graph/jaehoon/7569_토마토.cpp

[Week 8] Graph - 재훈

---

10-Dijkstra/Sunny/게임 맵 최단 거리.java
10-Dijkstra/Sunny/숫자 카드 나누기.java
10-Dijkstra/Sunny/특정 거리의 도시 찾기.java

---
- 18352 특정거리의 도시 찾기 실버2 https://www.acmicpc.net/problem/18352
- 프로그래머스 숫자 카드 나누기 https://school.programmers.co.kr/learn/courses/30/lessons/135807
- 프로그래머스 게임 맵 최단 거리 https://school.programmers.co.kr/learn/courses/30/lessons/1844
1문제는... 시간이 되면 지각으로 올릴게욤,,🥲

[Week 10] Dijkstra - 선희

---

10-Dijkstra/hayoun/백준1446.cpp
10-Dijkstra/hayoun/백준15686.cpp
10-Dijkstra/hayoun/백준1717.cpp
10-Dijkstra/hayoun/백준18352.cpp

- 필수문제
1446 지름길 골드5 https://www.acmicpc.net/problem/1446
18352 특정거리의 도시 찾기 실버2 https://www.acmicpc.net/problem/18352
- 자유문제
1717 집합의 표현 골드5 https://www.acmicpc.net/problem/1717
15686 치킨 배달 골드5 https://www.acmicpc.net/problem/15686

[Week10] Dijkstra- 하윤

---

11-Kruskal&Prim/jooyoung/1197_최소 스패닝 트리.py
11-Kruskal&Prim/jooyoung/1922_네트워크 연결.py
11-Kruskal&Prim/jooyoung/JadenCase 문자열 만들기.py
11-Kruskal&Prim/jooyoung/영어끝말잇기.py

- 1922 네트워크 연결 골드4 - https://www.acmicpc.net/problem/1922
- 1197 최소 스패닝 트리 골드 4 - https://www.acmicpc.net/problem/1197
- JadenCase 문자열 만들기 https://school.programmers.co.kr/learn/courses/30/lessons/12951?language=python3
- 영어끝말잇기 https://school.programmers.co.kr/learn/courses/30/lessons/12981

[week 11] 크루스칼, 프림 - 주영
